# Generated by Django 4.2.16 on 2024-11-21 23:01

from django.db import migrations
from django.utils.translation import gettext_lazy as _


def rename_default_gallery(apps, schema_editor):
    UserGallery = apps.get_model("gallery", "UserGallery")
    user_galleries = UserGallery.objects.filter(is_default=True, gallery__title="Galerie par défaut").select_related(
        "gallery", "user"
    )
    for user_gallery in user_galleries:
        user_gallery.gallery.title = _(f"Galerie par défaut de {user_gallery.user.username}")
        user_gallery.gallery.save()


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0008_normalize_user_gallery_mode"),
    ]

    operations = [
        migrations.RunPython(rename_default_gallery),
    ]
